server:
  port: 8081
spring:
  profiles:
    active: dev #切换不同环境的配置信息
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  jedis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri: mongodb://localhost:27017/zhihu

proxy.page.proxy.queueName: zhihu-proxy-page-proxy-list
target.page.proxy.queueName: zhihu-page-proxy-list